// <autogenerated>
//   This file was generated by T4 code generator DtosCodeScript.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>


using OSharp.Core.Data;
using System.ComponentModel;
using CDKX.Services.Core.Models.User;

namespace CDKX.Services.Core.Dtos.User
{
	public partial class ValidateCodeDto: IAddDto, IEditDto<int>
	{
        public System.Int32 Id { get; set; }
                            public System.String CodeKey { get; set; }
                                        public CDKX.Services.Core.Models.User.CodeType CodeType { get; set; }
                                        public CDKX.Services.Core.Models.User.ValidateType ValidateType { get; set; }
                                        public System.String Code { get; set; }
                    	}
}
